name: test7654321
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#aee1ff'
    - '#3c3d41'
    - '#a3a6a9'
    - '#feecb0'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
