name: test7654321
favicon: null
layout_spectrum: 0.29879625933244824
typography_spectrum: 0.722610110649839
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#aee1ff'
    - '#3c3d41'
    - '#a3a6a9'
    - '#feecb0'
  brandStrength: 0.125
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
